### PR TITLE
Fix: Ensure that tests work even if /tmp is not accessible

### LINKED ISSUE #588: Ensure that tests work even if `/tmp` is not accessible
`test/compiler.js` assumes that `/tmp` is always accessible. We should use a function that creates a temporary dir instead.

_Originally posted by @cameel in https://github.com/ethereum/solc-js/pull/566#discussion_r762097623_

### PR DESCRIPTION
**Pull request by adi611**
Fixes #588.

- [x] Created a temporary directory using `tmp` package inside function `createTempDir()`
- [x] Returned the name of temporary directory from the function `createTempDir()`
- [x] Replaced `/tmp` with name of created temporary directory `tempDir`

### CODE REVIEW

File: test/compiler.ts [hunk 1]
```diff
@@ -8,6 +8,12 @@ import wrapper from '../wrapper';
 
 const noRemoteVersions = (process.argv.indexOf('--no-remote-versions') >= 0);
 
+// use a function that creates a temporary dir instead of /tmp
+function createTempDir () {
+  const tmpDir = require('tmp').dirSync({ unsafeCleanup: true });
```
Comment (axic) [inline test/compiler.ts:13]: Please use an import statement above and not `require` here.

Comment (adi611) [reply test/compiler.ts:13]: Ok

**Comment by adi611** [comment]
It looks like there were some changes to `smtsolver.ts`

File: package.json [hunk 2]
```diff
@@ -59,6 +59,7 @@
   },
   "devDependencies": {
     "@types/node": "^16.11.7",
+    "@types/tmp": "^0.2.3",
```
Comment (axic) [inline package.json:62]: Was `tmp` not used in any other place we just had it `dependencies`?

**Comment by axic** [comment]
Please squash commits to a single one and use rebase instead of merge commit.

File: package.json (hunk 2 above)
Comment (adi611) [reply package.json:62]: Sorry but can you please be more clear about it?

Comment (axic) [reply package.json:62]: We have `tmp` in the `dependencies` in `package.json`. I suppose the typing package is needed if it is actually used within Typescript. I wonder why this one was not needed so far, which could mean that we do not actually use the package prior to this change.

Comment (adi611) [reply package.json:62]: This is actually quite funny lol.

**Comment by adi611** [comment]
Hi I was wondering whether I need to do any more changes for this to get merged.

**Review by cameel — CHANGES_REQUESTED** [review]
I'd adjust this a bit (see my comment) but other than that it looks fine to me and I can merge it when you apply these changes.

**Comment by adi611** [comment]
Done @cameel

**Comment by cameel** [comment]
Looks good, but can you also squash commits before I merge this? Our convention is that a every commit should be a single, logical change without going back and forth. Review fixes should be just squashed into the original commits.

**Comment by adi611** [comment]
> Looks good, but can you also squash commits before I merge this? Our convention is that a every commit should be a single, logical change without going back and forth. Review fixes should be just squashed into the original commits.

Done @cameel

**Review by cameel — APPROVED** [review]

**Comment by cameel** [comment]
Great. Thanks for the contribution!

**Comment by adi611** [comment]
Thanks for helping me along the way.
